### ISSUE TITLE
Credentials don't get set for HTTP authentication

### ISSUE THREAD

**Issue by bmacleod** [nagios-plugins-rabbitmq/nagios-plugins-rabbitmq#24]
I notice in check_rabbitmq_queue (presumably the other plugins too), credentials are set early with $ua->credentials().  Later on in the request method, a new HTTP::Request object is created, and then passed into $ua->request().

The credentials never make it to the HTTP::Request object, and therefore authentication always fails if auth is required.

Here is what I did to fix it (added the second line). You also don't need to worry about accounting for different realm names.

    = my $req = HTTP::Request->new(GET => $url);
    + $req->authorization_basic($p->opts->username, $p->opts->password);
    = my $res = $ua->request($req);

**Comment by barryib** [comment]
Closing this. fixed with #41
