### ISSUE TITLE
rabbitmq plugin and nrpe

### ISSUE THREAD

**Issue by markdelfin** [nagios-plugins-rabbitmq/nagios-plugins-rabbitmq#26]
I am using NRPE for nagios when I ran the check command locally on the rabbitmq machine, its working fine but when I the check ran remotely via nrpe. I get the error below

RABBITMQ_SERVER CRITICAL - Received 500 Can't connect to xx.xx.xx.xx:15672 (connect: Permission denied) for path: nodes/rabbit@xxxxxx

Thanks in Advance

**Comment by barryib** [comment]
Hello @markdelfin Is this issue still relevant?

**Comment by markdelfin** [comment]
Hi Thierno.

This can be close now. Thank you for the plugin

**Comment by barryib** [comment]
Thanks. I'm closing this.
