### ISSUE TITLE
No consumers condition

### ISSUE THREAD

**Issue by carbeman** [nagios-plugins-rabbitmq/nagios-plugins-rabbitmq#38]
It seems that is not possible verify the condition when there are no consumers.
It's possible add this behavior?

**Comment by martinnix** [comment]
Yes - I agree. The 4th parameter, according to the docs, is the minimum threshold for the number of consumers on a queue (while running check_rabbitmq_queue on a specific queue). Passing the parameter doesn't appear to trigger a warn/critical

**Comment by ewegene** [comment]
Yeah, this plugin isn't working correctly.

All four parameters (messages, messages_ready, messages_unacknowledged, consumers) are handled the same by the plugin.  If the defined value is greater than the metric that is collected trigger WARNING or CRITICAL.  Consumers is operating opposite to what is documented and is essentially useless.

**Comment by wiza** [comment]
It actually is working, it's just little weird. You need to specify the values as "4,4,4,4:" (no quotes, notice the colon). Colon makes the value mean "less than". Found it out by googling the documentation about nagios perl monitoring package :)

**Comment by barryib** [comment]
Hello,

As mentioned by @wiza, thresholds are actualy checked correctly. See the [monitoring plugins development guidelines](https://www.monitoring-plugins.org/doc/guidelines.html#THRESHOLDFORMAT).

Closing this issue.
