### ISSUE TITLE
add rpm build documentation

### ISSUE THREAD

**Issue by lobeck** [nagios-plugins-rabbitmq/nagios-plugins-rabbitmq#47]
I just noticed, that you removed the rpm spec file (https://github.com/jamesc/nagios-plugins-rabbitmq/commit/3c0f3e5a6ea5049f9c98b36573da763c5a32276b) and commented it with "removed spec file in favour of doing fpm packaging"

unfortunately i haven't found any documentation on how to build it with fpm

i already tried using:

```
perl Build.PL
perl Build dist
fpm -t rpm -s tar -v 2.0.2 -n nagios-plugins-rabbitmq --rpm-autoreq -a noarch nagios-plugins-rabbitmq-2.0.2.tar.gz
```

but this produces a rpm with incorrect file pathes. the same goes for cpan2rpm.

can please someone provide a quick documentation on how to build it correctly?

**Comment by barryib** [comment]
Hello @lobeck is this issue still relevant?

**Comment by lobeck** [comment]
Hi @barryib, i can't tell, as i haven't tried it since i created the issue and haven't checked back. So it's up to you, to decide on wether to close the ticket.

**Comment by barryib** [comment]
OK. I'm closing this issue. 

PS: I'm actually looking for a good way to automatically build packages from github release.
