### ISSUE TITLE
Access Refused

### ISSUE THREAD

**Issue by ximply** [nagios-plugins-rabbitmq/nagios-plugins-rabbitmq#52]
check_rabbitmq_aliveness -H lanrabbitmq -u admin -p admin
 RABBITMQ_ALIVENESS OK - vhost: /
 this is ok

But this is not ok.
check_rabbitmq_server -H lanrabbitmq -u admin -p admin
RABBITMQ_SERVER UNKNOWN - Access refused: nodes/rabbit@lanrabbitmq

Can you help me? Thanks in advance.

**Comment by barryib** [comment]
Hello @ximply, is this issue still relevant?

**Comment by barryib** [comment]
Closing this. You can re-open it when needed.
