### ISSUE TITLE
Unique queue name for aliveness-test

### ISSUE THREAD

**Issue by krjensen** [nagios-plugins-rabbitmq/nagios-plugins-rabbitmq#54]
A queue in a RabbitMQ cluster confuguration can only live on one host, so you can't check all nodes with aliveness-test. A fix to that would be a pre-fix to the queue name like: $hostname-aliveness-test

**Comment by barryib** [comment]
Hello @krjensen the aliveness-test is a rabbitmq management api endpoint. It says [in the doc](http://hg.rabbitmq.com/rabbitmq-management/raw-file/rabbitmq_v2_2_0/priv/www-api/help.html)

> Declares a test queue, then publishes and consumes a message. Does not delete the queue to avoid creating many mnesia transactions when this is repeatedly pinged. Intended for use by monitoring tools. If everything is working correctly, will return HTTP status 200

In that way, we can't define specific queue per node.

Plus, when you are in clusterised env, I think you would like to know if you can send message into the rabbitmq cluster and not to a particular node.

But if this is an important feature, we should look at how we should implement this into the aliveness script. May be, the script should:
- create queue (``aliveness-test-$hostname``)
- publish message
- do a basic get
- check if the receive message is the same of the sent one
- return nagios response

What do you think?

**Comment by barryib** [comment]
Closing this issue for now.
