### ISSUE TITLE
Is this repo still maintained and how can we contribute?

### ISSUE THREAD

**Issue by barryib** [nagios-plugins-rabbitmq/nagios-plugins-rabbitmq#59]
Hello @jamesc , Is this repository still maintained? There are some PR waiting for merge.

I was just wondering how community could contribute efficiently to this project.
- Is it worth to turn it into an organisation to allow some peoples to the committers?
- Simply add collaborators to the project?

Any suggestions?

**Comment by jamesc** [comment]
@barryib  I've not been able to dedicate much time to maintaining it and don't use the plugins in my current job.

I moved them to a new organization: https://github.com/nagios-plugins-rabbitmq/nagios-plugins-rabbitmq and invited you to it.

I'll update the README to ask for any other maintainers to open an issue for them to be added.

Thanks

**Comment by barryib** [comment]
Thanks @jamesc for that move. I'll take time this week to review some PR.
