### ISSUE TITLE
The future repo structure

### ISSUE THREAD

**Issue by barryib** [nagios-plugins-rabbitmq/nagios-plugins-rabbitmq#62]
Hello @jamesc,

I was wondering how we could manage this github repo. In fact, start with clean unmaintained branches.

In that way, is these branches still maintained and was there purposes:
- jc/3.x-updates
- rabbitmq-2.x (now a stale branch)

For now, I've noticed that the **Nagios::plugin** is still used even it is deprecated in favor of **Monitoring::plugin**. So I think that we should maintained two branches as follow:
- **master:** A stable branche with the perl **Monitoring::plugin**
- **perl-nagios-plugin:** A stable branche with the **Nagios::plugin**

What do you think? Any other ideas?

**Comment by jamesc** [comment]
Hi - the rabbitmq-2.x was the branch from which I cut some 1.2.x releases for rabbitmq 2.x (where the headers used for auth were different).  I feel like we can probably leave it as is or remove it.

We can delete the jc/3.x-updates - it was a WIP branch I had for doing some changes to support RabbitMQ 3.x during the transition.

I think it's a good idea to have a branch for the 2.X releases based on `perl-nagios-plugin` and then do a 3.0.0 release from master based on `Monitoring::Plugin`

**Comment by barryib** [comment]
Hello,

I propose to remove the rabbitma-2x branch.

I don't have any numbers, but I don't think that anyone are still using
RabbitMQ 2.x. For that reason, I think we should focus on the 3.x version.

In another hand, the move from Nagio::Plugin to Monitoring:: Plugin is
still on going. So we should probably backport changes on that branch
during the transition.

It would be great if we only maintain 2 branches (both for RabbitMQ 3.x).
One for the monitoring plugin and the 2nd for the nagios plugin.

Regards,
Thierno
Le 12 avr. 2016 10:05, "James Casey" <notifications@github.com> a écrit :

Hi - the rabbitmq-2.x was the branch from which I cut some 1.2.x releases
for rabbitmq 2.x (where the headers used for auth were different). I feel
like we can probably leave it as is or remove it.

We can delete the jc/3.x-updates - it was a WIP branch I had for doing some
changes to support RabbitMQ 3.x during the transition.

I think it's a good idea to have a branch for the 2.X releases based on
perl-nagios-plugin and then do a 3.0.0 release from master based on
Monitoring::Plugin

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/nagios-plugins-rabbitmq/nagios-plugins-rabbitmq/issues/62#issuecomment-208770558>

**Comment by barryib** [comment]
Hello @jamesc,

I've deleted ``rabbitmq-2x`` and ``jc/3.x-updates`` banches.

Now we've got 2 branches, one for ``Monitoring::Plugin`` and the 2nd for ``Nagios::Plugin``.

Cheers.
