### ISSUE TITLE
check_rabbitmq_cluster: add expected nodes in cluster

### ISSUE THREAD

**Issue by barryib** [nagios-plugins-rabbitmq/nagios-plugins-rabbitmq#68]
Check if expected nodes are running within the cluster. The node list can be a comma separated list.

**Comment by xcorp** [comment]
This code does not work as expected,
I've moded the code to print some debug
`if (defined($p->opts->nodes)) {
    my @nodes = split(',', $p->opts->nodes);
    my @excluded_nodes = diff(\@nodes, \@{ $values->{'running_nodes'} });
    my $nb_excluded_nodes = @excluded_nodes;
    print "Input: @nodes\n";
    print "API:   @{ $values->{'running_nodes'}}\n";
    print "DIFF:  @excluded_nodes\n";
    print "$nb_excluded_nodes\n";
    ($code, $message) = (OK, "All nodes are running");
    ($code, $message) = (CRITICAL, "$nb_excluded_nodes failed cluster node: " . join(',', @excluded_nodes)) if($nb_excluded_nodes ne 0);
}`

This is the ouput I get
`
./check_rabbitmq_cluster -H mb.icomera.com --ssl --port 443 -u user  -p password  -n rabbit@prod-mq-1,rabbit@prod-mq-2,rabbit@prod-mq-stat 2>&1 | grep -ve "/usr/share" -e "/usr/local" -e "/usr/lib"
Input: rabbit@prod-mq-1 rabbit@prod-mq-2 rabbit@prod-mq-stat
API:   rabbit@prod-mq-1 rabbit@prod-mq-2 rabbit@prod-mq-stat
DIFF:  rabbit@prod-mq-1 rabbit@prod-mq-2 rabbit@prod-mq-stat
3
RABBITMQ_CLUSTER CRITICAL - 3 failed cluster node: rabbit@prod-mq-1,rabbit@prod-mq-2,rabbit@prod-mq-stat
`
