### ISSUE TITLE
Response from objects longer than 4096 char...

### ISSUE THREAD

**Issue by warwing** [nagios-plugins-rabbitmq/nagios-plugins-rabbitmq#73]
Hi, 

when calling check_rabbitmq_objects, I sometimes get an error like:

_unexpected end of string while parsing JSON string, at character offset 4096 (before "(end of string)") at [..] check_rabbitmq_objects line 131._

The rabbitmq call returns without an error - looks like "my $bodyref = decode_json $res->content;" can't handle responses longer than 4096 characters.

Any idea how to fix this?

Thanks :)

**Comment by barryib** [comment]
Hello @warwing,

by default, there is no limit on the  body size for encoding or decoding a json object. It could be a mal formatted json output from the api.

- What is your OS and RabbitMQ version?
- What object are your querying?
- Can you provide the json output for that object by querying the api directly (you can dump the `$res->content`at the line 131)?

**Comment by warwing** [comment]
Hi,

yes, I can query the objects via curl - and the output seems to be valid - please see attachment - just removed details about installation...

We're using debian 8, rabbitmq 3.6.2 and erlang 18.3 and on the monitoring server perl 5.20.2.

Currently I don't restrict the type of queried objects - so everything will be fetched...

[rabbitmq.txt](https://github.com/nagios-plugins-rabbitmq/nagios-plugins-rabbitmq/files/285793/rabbitmq.txt)

**Comment by barryib** [comment]
Hello @warwing ,

I've tried to check your json output and everything sounds to be ok.

the check_rabbitmq_objects's script pull these endpoints: *vhost*, *exchange*, *binding*, *queue*, *channel*. So your problem could came from one of those.

Can you please hack your script as follow to print out the body content:
```perl
    my $bodyref = decode_json $res->content;
    print $res->content . "\n\n\n";
    return($res->code, $bodyref);
```
This will print out 5 json outputs. I think you can find something interesting.

**Comment by barryib** [comment]
@warwing i'm closing this issue. Feel free to open it again if needed.
