### ISSUE TITLE
Specify alert if connections goes under a certain number?

### ISSUE THREAD

**Issue by rbjoergensen** [nagios-plugins-rabbitmq/nagios-plugins-rabbitmq#86]
Is there no way to specify a rule for when my connections drop down below a certain value?

**Comment by barryib** [comment]
@rbjoergensen please see the [`check_rabbitmq_connections` script](https://github.com/nagios-plugins-rabbitmq/nagios-plugins-rabbitmq/blob/master/scripts/check_rabbitmq_connections).

**Comment by barryib** [comment]
closing this. For any question, you have the [gitter channel](https://gitter.im/nagios-plugins-rabbitmq/nagios-plugins-rabbitmq?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
