### ISSUE TITLE
check_rabbitmq_server fails with RABBITMQ_SERVER UNKNOWN Not found: nodes/rabbit@<hostname>

### ISSUE THREAD

**Issue by jgoetz** [nagios-plugins-rabbitmq/nagios-plugins-rabbitmq#87]
I have installed the plugin on my Nagios server running RHEL 6 following the instructions [here](http://www.thegeekstuff.com/2013/12/nagios-plugins-rabbitmq/) and [here ](https://medium.com/devops-process-and-tools/procedure-to-install-nagios-rabbtimq-plugins-and-monitor-rabbitmq-stats-with-nagios-1ed37183d6b). 
I can run the rabbitmq_admin commands from the rabbitmq server in question: 

[root@rmqserver]> curl -i -u rabbitmq_user:******** http://localhost:15672/api/nodes

so I know the user and password are valid.  

When I try to run from my nagios server: 
[root@nagios]\# cd /usr/local/nagios/libexec/nagios-plugins-rabbitmq/scripts/
[root@nagios]\# ./check_rabbitmq_server -H my.rabbithost.edu -u rabbitmq_user -p *******

I get this response:
>RABBITMQ_SERVER UNKNOWN - Not found: nodes/rabbit@my.rabbithost.edu

The logs show no entries for this attempt.

The rabbitmq Management UI shows (near the top right corner): Cluster: rabbit@my.rabbithost.edu

When I change to use default user guest:guest login:
[root@nagios]# check_rabbitmq_server -H my.rabbithost.edu

the logs show:
> =WARNING REPORT==== 10-Aug-2017::14:34:08 ===
> HTTP access denied: user 'guest' - User can only log in via localhost
> 
> =ERROR REPORT==== 10-Aug-2017::14:34:08 ===
> webmachine error: path="/api/nodes/rabbit@my.rabbithost.edu"

which is expected, but shows the plugin is connecting and communicating with the rmq server. 

Any ideas what could be the problem? Thanks in advance.

**Comment by barryib** [comment]
@jgoetz Is your node name `rabbit@my.rabbithost.edu` (not your cluster name)?

What's the output of `curl -u rabbitmq_user:******** http://localhost:15672/api/nodes`? Do you have a node name with `rabbit@my.rabbithost.edu`?

**Comment by jgoetz** [comment]
According to `rabbitmqctl environment`, my node name is rabbit@rabbithost
(I'm not permitted to display my real hostname outside of my intranet, so I replaced my real hostname with rabbithost). 
I don't have a cluster, just a single RabbitMQ server, which I suppose could be classified as a minimal cluster...

[{"cluster_links":[],"disk_free":5697142784,"disk_free_details":{"rate":0.0},"fd_used":62,"fd_used_details":{"rate":-0.4},"io_read_avg_time":0.0,"io_read_avg_time_details":{"rate":0.0},"io_read_bytes":2146127,"io_read_bytes_details":{"rate":0.0},"io_read_count":31,"io_read_count_details":{"rate":0.0},"io_seek_avg_time":0.025130434782608697,"io_seek_avg_time_details":{"rate":0.0},"io_seek_count":24,"io_seek_count_details":{"rate":0.0},"io_sync_avg_time":0.0,"io_sync_avg_time_details":{"rate":0.0},"io_sync_count":2,"io_sync_count_details":{"rate":0.0},"io_write_avg_time":0.0,"io_write_avg_time_details":{"rate":0.0},"io_write_bytes":3648,"io_write_bytes_details":{"rate":0.0},"io_write_count":2,"io_write_count_details":{"rate":0.0},"mem_used":80332888,"mem_used_details":{"rate":28619.2},"mnesia_disk_tx_count":11,"mnesia_disk_tx_count_details":{"rate":0.0},"mnesia_ram_tx_count":3760,"mnesia_ram_tx_count_details":{"rate":0.0},"msg_store_read_count":20,"msg_store_read_count_details":{"rate":0.0},"proc_used":211,"proc_used_details":{"rate":0.0},"queue_index_journal_write_count":3,"queue_index_journal_write_count_details":{"rate":0.0},"queue_index_read_count":5,"queue_index_read_count_details":{"rate":0.0},"queue_index_write_count":1,"queue_index_write_count_details":{"rate":0.0},"sockets_used":0,"sockets_used_details":{"rate":0.0},"partitions":[],"os_pid":"2329","fd_total":1024,"sockets_total":829,"mem_limit":1607434240,"mem_alarm":false,"disk_free_limit":50000000,"disk_free_alarm":false,"proc_total":1048576,"rates_mode":"basic","uptime":2461774656,"run_queue":0,"processors":2,"exchange_types":[{"name":"topic","description":"AMQP topic exchange, as per the AMQP specification","enabled":true},{"name":"headers","description":"AMQP headers exchange, as per the AMQP specification","enabled":true},{"name":"direct","description":"AMQP direct exchange, as per the AMQP specification","enabled":true},{"name":"fanout","description":"AMQP fanout exchange, as per the AMQP specification","enabled":true}],"auth_mechanisms":[{"name":"PLAIN","description":"SASL PLAIN authentication mechanism","enabled":true},{"name":"AMQPLAIN","description":"QPid AMQPLAIN mechanism","enabled":true},{"name":"RABBIT-CR-DEMO","description":"RabbitMQ Demo challenge-response authentication mechanism","enabled":false}],"applications":[{"name":"amqp_client","description":"RabbitMQ AMQP Client","version":"3.6.1"},{"name":"asn1","description":"The Erlang ASN1 compiler version 4.0.1","version":"4.0.1"},{"name":"compiler","description":"ERTS  CXC 138 10","version":"6.0.2"},{"name":"crypto","description":"CRYPTO","version":"3.6.2"},{"name":"inets","description":"INETS  CXC 138 49","version":"6.1"},{"name":"kernel","description":"ERTS  CXC 138 10","version":"4.1.1"},{"name":"mnesia","description":"MNESIA  CXC 138 12","version":"4.13.2"},{"name":"mochiweb","description":"MochiMedia Web Server","version":"2.13.0"},{"name":"os_mon","description":"CPO  CXC 138 46","version":"2.4"},{"name":"public_key","description":"Public key infrastructure","version":"1.1"},{"name":"rabbit","description":"RabbitMQ","version":"3.6.1"},{"name":"rabbit_common","description":"","version":"3.6.1"},{"name":"rabbitmq_management","description":"RabbitMQ Management Console","version":"3.6.1"},{"name":"rabbitmq_management_agent","description":"RabbitMQ Management Agent","version":"3.6.1"},{"name":"rabbitmq_web_dispatch","description":"RabbitMQ Web Dispatcher","version":"3.6.1"},{"name":"ranch","description":"Socket acceptor pool for TCP protocols.","version":"1.2.1"},{"name":"sasl","description":"SASL  CXC 138 11","version":"2.6.1"},{"name":"ssl","description":"Erlang/OTP SSL application","version":"7.2"},{"name":"stdlib","description":"ERTS  CXC 138 10","version":"2.7"},{"name":"syntax_tools","description":"Syntax tools","version":"1.7"},{"name":"webmachine","description":"webmachine","version":"1.10.3"},{"name":"xmerl","description":"XML parser","version":"1.3.9"}],"contexts":[{"description":"RabbitMQ Management","path":"/","port":"15672"}],"log_file":"/var/log/rabbitmq/rabbit@rabbithost.log","sasl_log_file":"/var/log/rabbitmq/rabbit@rabbithost-sasl.log","db_dir":"/var/lib/rabbitmq/mnesia/rabbit@rabbithost","config_files":["/etc/rabbitmq/rabbitmq.config (not found)"],"net_ticktime":60,"enabled_plugins":["rabbitmq_management"],"name":"rabbit@rabbithost","type":"disc","running":true}]
  
Thanks for your time and assistance!

**Comment by jgoetz** [comment]
Your question gave me a clue to try the -n <nodename> in the command line. Thus, when I run:
[root@nagios]# ./check_rabbitmq_server -H rabbithost.edu -u rabbitmq_user -p "******" -n rabbithost 
it responds with:
RABBITMQ_SERVER OK - Memory OK (21.19%) Process OK (0.02%) FD OK (6.35%) Sockets OK (0.36%) | Memory=21.19%;80;90 Process=0.02%;80;90 FD=6.35%;80;90 Sockets=0.36%;80;90

so, I must use the node name in my Nagios setup. Thanks for the hint!!

**Comment by barryib** [comment]
Thanks. I'm closing this issue.
