### ISSUE TITLE
Option with "!" doesn't work

### ISSUE THREAD

**Issue by Julien-Rozet** [nagios-plugins-rabbitmq/nagios-plugins-rabbitmq#95]
Hi,

Options with "!" at the end (`--ssl!`, `--ssl_strict!` and `--ignore!`) doesn't work!
I get an error:
```
Unknown option: ssl!
Unknown option: ssl_strict!
Unknown option: ignore!
```

**Comment by hdep** [comment]
Hi

same issue with :  
```
--proxy!
Unknown option: proxy!
```

**Comment by hdep** [comment]
@Julien-Rozet I think I found the issue : 
According tot https://metacpan.org/pod/Monitoring::Plugin::Getopt#ARGUMENTS

if you use  `--no-proxy `or `--no-ssl` it works. 

the issue come from the help page.

**Comment by Julien-Rozet** [comment]
You're right, that's work! :)
